CRM_ASP/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CRM_MODEL_LIB;

namespace CRM_ASP.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View(new AboutInfo {
                name="CRM project",
                adress="Автомобилистов 56, г.Пыть-ях",
                tel="2233223",
                fax="435434",
                email="mizantrop@gmail.com",
                manager = "Маврикий Евграфович Цепало"
            });
        }
    }
}

CRM_ASP/Controllers/BidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CRM_MODEL_LIB;
using CRM_ASP.Models;
using CRM_ASP.Models.ViewModels;
using CRM_ASP.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace CRM_ASP.Controllers
{
    [Authorize]
    public class BidController : Controller
    {
        private IBidRepository repository;
        private IEnumerable<BidStatus> statuses;
        public int PageSize = 3;

        public BidController(IBidRepository repo, EFStatuses sts)
        {
            repository = repo;
            statuses = sts.Statuses;

        }

        public IActionResult Show(int id)
        {
            var bid = repository.Bids.FirstOrDefault(a => a.id == id);
            return View(bid);
        }

        public IActionResult All(int? StatusId,int productPage = 1)
        {
            var r_url = HttpContext.Request.PathAndQuery();
            if (HttpContext.Request.Method == "POST")
            {
                r_url += '?';
                if (!(StatusId is null)) r_url += $"StatusId={StatusId}&";
                r_url += $"productPage={productPage}";
            }


            ViewBag.r_url = r_url;
            ViewBag.ActionName = RouteData.Values["action"].ToString();
            var query = repository.Bids.Where(b => StatusId == null || b.BidStatusId == StatusId);
            return View("List", new BidsListViewModel
            {
                Bids = query.Skip((productPage - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = productPage,
                    ItemsPerPage = PageSize,
                    TotalItems = query.Count()
                },
                BidStatuses = statuses,
                FilterInfo = new FilterInfo
                {
                    BidStatusId = StatusId
                }
            });
        }

        public IActionResult ConcreteDay(int date_ofset, int? StatusId, int productPage = 1)
        {
            var r_url = HttpContext.Request.PathAndQuery();
            if (HttpContext.Request.Method == "POST")
            {
                r_url += '?';
                if (!(StatusId is null)) r_url += $"StatusId={StatusId}&";
                r_url += $"date_ofset={date_ofset}&";
                r_url += $"productPage={productPage}";
            }
            ViewBag.r_url = r_url;

            ViewBag.ActionName = RouteData.Values["action"].ToString();
            var query = repository.GetConcreteDayBids(date_ofset).Where(b => StatusId == null || b.BidStatusId == StatusId);
            return View("List", new BidsListViewModel
            {
                Bids = query.Skip((productPage - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = productPage,
                    ItemsPerPage = PageSize,
                    TotalItems = query.Count()
                },
                BidStatuses = statuses,
                FilterInfo = new FilterInfo
                {
                    DateOfset = date_ofset,
                    BidStatusId = StatusId
                }
            });
        }

        public IActionResult LastDays(int days_left, int? StatusId, int productPage = 1)
        {
            var r_url = HttpContext.Request.PathAndQuery();
            if (HttpContext.Request.Method == "POST")
            {
                r_url += '?';
                if (!(StatusId is null)) r_url += $"StatusId={StatusId}&";
                r_url += $"days_left={days_left}&";
                r_url += $"productPage={productPage}";
            }
            ViewBag.r_url = r_url;

            ViewBag.ActionName = RouteData.Values["action"].ToString();
            var query = repository.GetLastBids(days_left).Where(b => StatusId == null || b.BidStatusId == StatusId);
            return View("List", new BidsListViewModel
            {
                Bids = query.Skip((productPage - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = productPage,
                    ItemsPerPage = PageSize,
                    TotalItems = query.Count()
                },
                BidStatuses = statuses,
                FilterInfo = new FilterInfo
                {
                    DaysLeft = days_left,
                    BidStatusId = StatusId
                }
            });
        }

        public IActionResult DateRange(DateTime left_date, int? StatusId, DateTime right_date, int productPage = 1)
        {
            var r_url = HttpContext.Request.PathAndQuery();
            if (HttpContext.Request.Method == "POST")
            {
                r_url += '?';
                if (!(StatusId is null)) r_url += $"StatusId={StatusId}&";
                r_url += $"left_date={left_date.ToString("MM.dd.yyyy").Replace(".","%2F")}&";
                r_url += $"right_date={right_date.ToString("MM.dd.yyyy").Replace(".", "%2F")}&";
                r_url += $"productPage={productPage}";
            }
            ViewBag.r_url = r_url;

            ViewBag.ActionName = RouteData.Values["action"].ToString();
            var query = repository.GetDateRangeBids(left_date, right_date).Where(b => StatusId == null || b.BidStatusId == StatusId);
            return View("List", new BidsListViewModel
            {
                Bids = query.Skip((productPage - 1) * PageSize).Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = productPage,
                    ItemsPerPage = PageSize,
                    TotalItems = query.Count()
                },
                BidStatuses = statuses,
                FilterInfo = new FilterInfo
                {
                    LeftDate = left_date,
                    RightDate = right_date,
                    BidStatusId = StatusId
                }
            });
        }

        public IActionResult Update(Bid bid, string returnUrl)
        {
            repository.UpdateStatus(bid);
            return Redirect(returnUrl);
        }
    }
}

CRM_ASP/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CRM_MODEL_LIB;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace CRM_ASP.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        private IArticleRepository repository;

        public BlogController(IArticleRepository repo)
        {
            repository = repo;
        }

        [AllowAnonymous]
        public IActionResult Articles()
        {
            return View(repository.Articles);
        }

        [AllowAnonymous]
        public IActionResult Show(int id)
        {
            var article = repository.Articles.FirstOrDefault(a => a.id == id);
            return View(article);
        }

        public IActionResult Create()
        {
            return View(new Article());
        }

        [HttpPost]
        public IActionResult Create(Article article, IFormFile fileData)
        {

            if (fileData != null)
            {
                byte[] imageData = null;
                // считываем переданный файл в массив байтов
                using (var binaryReader = new BinaryReader(fileData.OpenReadStream()))
                {
                    imageData = binaryReader.ReadBytes((int)fileData.Length);
                }
                // установка массива байтов
                article.imageData = imageData;
            }

            repository.SaveArticle(article);
            return RedirectToAction(nameof(Articles));
        }
    }
}

CRM_ASP/Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CRM_MODEL_LIB;

namespace CRM_ASP.Controllers
{
    public class OfferController : Controller
    {
        private IOfferRepository repository;

        public OfferController(IOfferRepository repo)
        {
            repository = repo;
        }
        public IActionResult List()
        {
            return View(repository.Offers);
        }
    }
}

CRM_ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <!-- inside <head> -->
    <link rel="stylesheet" href="~/vendor.min.css" />
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <!-- at the end of <body> -->
    <script src="~/vendor.min.js"></script>
    <title>CRM project</title>
</head>
<body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top border-bottom" id="main-nav">
        <div class="container">
            <a asp-action="Index" asp-controller="Home" class="navbar-brand">CRM project</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    @if (User?.Identity?.IsAuthenticated ?? false)
                    {
                        <li class="nav-item">
                            <a asp-action="All" asp-controller="Bid" class="nav-link">Заявки</a>
                        </li>
                    }
                    <li class="nav-item">
                        <a asp-action="List" asp-controller="Offer" class="nav-link">Услуги</a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="List" asp-controller="Projects" class="nav-link">Проекты</a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="Articles" asp-controller="Blog" class="nav-link">Статьи</a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="Index" asp-controller="About" class="nav-link">Контакты</a>
                    </li>
                    @if (User?.Identity?.IsAuthenticated ?? false)
                    {
                        <li class="nav-item">
                            <a asp-action="Logout" asp-controller="Account" class="nav-link">Выйти</a>
                        </li>
                    }
                    @if (!User?.Identity?.IsAuthenticated ?? false)
                    {
                        <li class="nav-item">
                            <a asp-action="Login" asp-controller="Account" class="nav-link">Войти</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>


    <div>
        @RenderBody()
    </div>


    <div id="main-footer" class="row-fluid text-center p-4 col bg-dark border-top">
        <div class="navbar-inner">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <p>
                            Copyright &copy;
                            <span id="year"></span> CRM project
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Get the current year for the copyright
        $('#year').text(new Date().getFullYear());
    </script>

    <script>
        if ($(document).height() <= $(window).height())
        $("#main-footer").addClass("fixed-bottom");
    </script>
</body>
</html>